#!/usr/bin/env python3
# gen_pdf.py — AcquisitionOS Local Setup & Deployment Guide (Report route, ReportLab body)
# Cover: scripts/pdf-work/cover.pdf (HTML/Playwright, Template 01). Merge via pypdf.
import os, sys, hashlib
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
                                PageBreak, CondPageBreak, KeepTogether, XPreformatted)
from reportlab.platypus.tableofcontents import TableOfContents

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f2f1f0')
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')
HEADER_FILL   = colors.HexColor('#504933')
COVER_BLOCK   = colors.HexColor('#867b5a')
BORDER        = colors.HexColor('#cfcab8')
ICON          = colors.HexColor('#8c7e52')
ACCENT        = colors.HexColor('#87702a')
ACCENT_2      = colors.HexColor('#3a95b4')
TEXT_PRIMARY  = colors.HexColor('#1c1c1a')
TEXT_MUTED    = colors.HexColor('#78766f')
SEM_ERROR     = colors.HexColor('#92453e')

MARGIN = 1.0 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
DOC_TITLE = 'AcquisitionOS - Local Setup and Deployment Guide'
OUT_BODY = '/home/z/my-project/scripts/pdf-work/body.pdf'
OUT_FINAL = '/home/z/my-project/download/ACQUISITIONOS-LOCAL-SETUP.pdf'

# ── Styles (Report brief component reference) ──
h1_style = ParagraphStyle('H1', fontName='FreeSerif', fontSize=20, leading=26,
                          textColor=TEXT_PRIMARY, spaceBefore=18, spaceAfter=10)
h2_style = ParagraphStyle('H2', fontName='FreeSerif', fontSize=14, leading=19,
                          textColor=HEADER_FILL, spaceBefore=14, spaceAfter=6)
body_style = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5, leading=16.5,
                            textColor=TEXT_PRIMARY, alignment=TA_JUSTIFY, spaceAfter=8)
bullet_style = ParagraphStyle('Bullet', fontName='FreeSerif', fontSize=10.5, leading=16,
                              textColor=TEXT_PRIMARY, leftIndent=16, bulletIndent=4, spaceAfter=4)
code_style = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=7.6, leading=10.6,
                            textColor=TEXT_PRIMARY, alignment=TA_LEFT)
cell_style = ParagraphStyle('Cell', fontName='FreeSerif', fontSize=9, leading=12.5,
                            textColor=TEXT_PRIMARY, alignment=TA_LEFT)
cellb_style = ParagraphStyle('CellB', fontName='FreeSerif', fontSize=9, leading=12.5,
                             textColor=TEXT_PRIMARY, alignment=TA_LEFT)
head_style = ParagraphStyle('TblHead', fontName='FreeSerif', fontSize=9.2, leading=12.5,
                            textColor=colors.white, alignment=TA_LEFT)
cap_style = ParagraphStyle('Cap', fontName='FreeSerif', fontSize=8.5, leading=12,
                           textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=3, spaceAfter=6)
toc_h_style = ParagraphStyle('TOCTitle', fontName='FreeSerif', fontSize=22, leading=28,
                             textColor=TEXT_PRIMARY, spaceAfter=14)

def esc(t):
    return t.replace('&', '&').replace('<', '<').replace('>', '>')

def add_heading(story, text, level=0):
    key = 'h_' + hashlib.md5(text.encode()).hexdigest()[:8]
    st = h1_style if level == 0 else h2_style
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, esc(text)), st)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    story.append(p)

def make_table(story, headers, rows, ratios, caption=None, font=9):
    n = len(headers)
    col_w = [r * AVAIL_W for r in ratios]
    scale = (AVAIL_W * 0.999) / sum(col_w)
    col_w = [w * scale for w in col_w]
    assert sum(col_w) <= AVAIL_W + 0.5, 'table too wide'
    cs = ParagraphStyle('C%d' % font, parent=cell_style, fontSize=font, leading=font + 3.4)
    hs = ParagraphStyle('H%d' % font, parent=head_style, fontSize=font + 0.2, leading=font + 3.6)
    data = [[Paragraph('<b>%s</b>' % esc(h), hs) for h in headers]]
    for row in rows:
        data.append([Paragraph(esc(c) if not c.startswith('<') else c, cs) for c in row])
    t = Table(data, colWidths=col_w, repeatRows=1, hAlign='CENTER')
    style = [
        ('BACKGROUND', (0, 0), (-1, 0), HEADER_FILL),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        style.append(('BACKGROUND', (0, i), (-1, i), colors.white if i % 2 == 1 else TABLE_STRIPE))
    t.setStyle(TableStyle(style))
    story.append(Spacer(1, 10))
    story.append(t)
    if caption:
        story.append(Spacer(1, 4))
        story.append(Paragraph(esc(caption), cap_style))
    story.append(Spacer(1, 10))

def make_code(story, code_text):
    lines = []
    for raw in code_text.split('\n'):
        while len(raw) > 88:
            cut = raw.rfind(" ", 60, 88)
            cut = cut if cut > 0 else 88
            lines.append(raw[:cut])
            raw = '  ' + raw[cut:].lstrip()
        lines.append(raw)
    pre = XPreformatted(esc('\n'.join(lines)), code_style)
    box = Table([[pre]], colWidths=[AVAIL_W * 0.96], hAlign='CENTER')
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), CARD_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 2.4, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(Spacer(1, 6))
    story.append(box)
    story.append(Spacer(1, 8))

def make_callout(story, text):
    p = Paragraph(esc(text), ParagraphStyle('CO', parent=body_style, fontSize=9.6,
                                            leading=14.5, alignment=TA_LEFT, spaceAfter=0))
    box = Table([[p]], colWidths=[AVAIL_W * 0.96], hAlign='CENTER')
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), TABLE_STRIPE),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(Spacer(1, 6))
    story.append(box)
    story.append(Spacer(1, 8))

def render_blocks(story, blocks):
    pending_heading = None
    for b in blocks:
        kind = b[0]
        el = None
        if kind == 'h1':
            story.append(CondPageBreak(AVAIL_H * 0.25))
            pending_heading = ('h1', b[1])
            continue
        elif kind == 'h2':
            pending_heading = ('h2', b[1])
            continue
        elif kind == 'p':
            el = [Paragraph(b[1], body_style)]
        elif kind == 'bullets':
            el = [Paragraph('• ' + item, bullet_style) for item in b[1]]
            el.append(Spacer(1, 4))
        elif kind == 'table':
            make_table(story, b[1], b[2], b[3], b[4] if len(b) > 4 else None)
        elif kind == 'code':
            make_code(story, b[1])
        elif kind == 'callout':
            make_callout(story, b[1])
        if el is not None:
            if pending_heading:
                lvl, txt = pending_heading
                lvl = 0 if lvl == 'h1' else 1
                first = el[0]
                story.append(KeepTogether([_heading(lvl, txt), first]))
                story.extend(el[1:])
                pending_heading = None
            else:
                story.extend(el)
    if pending_heading:
        lvl, txt = pending_heading
        story.append(_heading(0 if lvl == 'h1' else 1, txt))

def _heading(lvl, txt):
    lvl = int(lvl)
    key = 'h_' + hashlib.md5(txt.encode()).hexdigest()[:8]
    st = h1_style if lvl == 0 else h2_style
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, esc(txt)), st)
    p.bookmark_name = key
    p.bookmark_level = lvl
    p.bookmark_text = txt
    p.bookmark_key = key
    return p

class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))
            if text.startswith('1. '):
                self._first_body_page = self.page

ROMAN = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi'}

def on_page(canvas, doc):
    canvas.saveState()
    # Header: title left + accent rule
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.62 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.70 * inch, PAGE_W - MARGIN, PAGE_H - 0.70 * inch)
    # Footer: light rule + page number (roman for front matter, arabic reset for body)
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.6)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, 'AcquisitionOS Engineering')
    fbp = getattr(doc, '_first_body_page', 2)
    if doc.page < fbp:
        num = ROMAN.get(doc.page, str(doc.page))
    else:
        num = str(doc.page - fbp + 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, num)
    canvas.restoreState()

def build():
    from pdf_body_data1 import CHAPTERS_1
    from pdf_body_data2 import CHAPTERS_2
    doc = TocDocTemplate(OUT_BODY, pagesize=A4,
                         leftMargin=MARGIN, rightMargin=MARGIN,
                         topMargin=MARGIN, bottomMargin=MARGIN,
                         title=DOC_TITLE, author='Z.ai', creator='Z.ai',
                         subject='Verified zero-to-local setup, environment and deployment documentation')
    story = []
    # TOC page (front matter, level-0 only -> single page)
    story.append(Paragraph('<b>Table of Contents</b>', toc_h_style))
    toc = TableOfContents()
    toc.levelStyles = [ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=10.5,
                                      leading=17.5, leftIndent=6, textColor=TEXT_PRIMARY)]
    story.append(toc)
    story.append(PageBreak())
    first = True
    for title, blocks in CHAPTERS_1 + CHAPTERS_2:
        num = CHAPTERS_1 + CHAPTERS_2
        blocks = [b for b in blocks]
        # prepend numbered h1 by rewriting first h1
        blocks[0] = ('h1', title)
        if first:
            # mark first chapter heading page for footer numbering
            blocks = [blocks[0]] + blocks[1:]
            first = False
        render_blocks(story, blocks)
    doc.multiBuild(story, onFirstPage=on_page, onLaterPages=on_page)
    print('body built:', OUT_BODY)

if __name__ == '__main__':
    build()
