'use client';

import React, { useEffect, useRef } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { useLegalStore, type LegalPage } from '@/lib/legal-store';
import {
  Shield,
  FileText,
  Lock,
  Cookie,
  ArrowLeft,
} from 'lucide-react';

// ════════════════════════════════════════════════════════════════════
// LEGAL CONTENT — Privacy Policy
// ════════════════════════════════════════════════════════════════════

function PrivacyPolicyContent() {
  return (
    <article className="prose prose-sm dark:prose-invert max-w-none text-justify">
      <p className="text-sm text-muted-foreground mb-6">
        <strong>Effective Date:</strong> March 1, 2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> March 1, 2025
      </p>

      <p className="text-sm leading-relaxed">
        AcquisitionOS (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI-powered B2B lead discovery and outreach platform (the &quot;Service&quot;). Please read this policy carefully. By using AcquisitionOS, you agree to the practices described herein.
      </p>

      <Separator className="my-6" />

      {/* Section 1 */}
      <h3 className="text-base font-semibold mt-6 mb-3">1. Information We Collect</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">1.1 Information You Provide</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Account Information:</strong> Name, email address, phone number, company name, country, and timezone when you register for an account.</li>
        <li><strong>Business Information:</strong> Details about your business, target markets, ideal customer profiles, and lead preferences that you provide to configure the Service.</li>
        <li><strong>Lead Data:</strong> Information about potential leads and prospects that you input, import, or discover through our platform, including business names, contact details, and company information.</li>
        <li><strong>Payment Information:</strong> Billing address, GST/VAT numbers, and payment method details processed securely through our payment partners (Stripe, Razorpay). We do not store full credit card numbers on our servers.</li>
        <li><strong>Communications:</strong> Outreach messages, email templates, and communication content you create or send through the Service.</li>
        <li><strong>Integration Data:</strong> Data accessed through connected integrations including Gmail (emails, contacts), Google Calendar (events, availability), and Telegram (messages, notifications).</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">1.2 Information Collected Automatically</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Usage Data:</strong> Features accessed, pages viewed, actions taken, time spent on the platform, click patterns, and interaction data.</li>
        <li><strong>Device Information:</strong> Browser type, operating system, device type, screen resolution, and unique device identifiers.</li>
        <li><strong>Log Data:</strong> IP address, access timestamps, referrer URLs, and server request logs.</li>
        <li><strong>Cookies and Tracking:</strong> See our Cookie Policy for details on how we use cookies and similar tracking technologies.</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">1.3 Information Generated by AI</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Lead Scores:</strong> AI-generated scores and ratings for discovered leads based on your criteria.</li>
        <li><strong>Analysis Results:</strong> AI-generated insights, recommendations, and analysis of lead data, company information, and market trends.</li>
        <li><strong>Generated Content:</strong> AI-drafted outreach messages, email templates, and suggested communication strategies.</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 2 */}
      <h3 className="text-base font-semibold mt-6 mb-3">2. How We Use Your Information</h3>
      <p className="text-sm leading-relaxed mb-3">We use the information we collect for the following purposes:</p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Service Delivery:</strong> To provide, maintain, and improve the AcquisitionOS platform, including AI-powered lead discovery, enrichment, scoring, and outreach capabilities.</li>
        <li><strong>Account Management:</strong> To create and manage your account, process payments, handle credit allocations, and manage subscriptions (Free, Pro, and Enterprise tiers).</li>
        <li><strong>Communication:</strong> To send you service-related notifications, credit alerts, trial reminders, security alerts, and support responses.</li>
        <li><strong>Personalization:</strong> To customize your experience, improve AI model accuracy for your use case, and provide relevant lead recommendations.</li>
        <li><strong>Analytics:</strong> To analyze usage patterns, measure feature adoption, and generate insights to improve our Service.</li>
        <li><strong>Security:</strong> To detect and prevent fraud, unauthorized access, and other illegal activities, and to protect the security of our users and platform.</li>
        <li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, legal processes, or governmental requests.</li>
        <li><strong>AI Improvement:</strong> To train and improve our AI models for lead scoring, enrichment, and content generation (anonymized and aggregated only for Enterprise customers; individual data is not used for training without explicit consent).</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 3 */}
      <h3 className="text-base font-semibold mt-6 mb-3">3. Information Sharing</h3>
      <p className="text-sm leading-relaxed mb-3">We do not sell your personal information. We may share your information with:</p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Service Providers:</strong> Third-party vendors who perform services on our behalf, including cloud hosting (AWS, Vercel), payment processing (Stripe, Razorpay), email delivery (Gmail SMTP), and analytics (PostHog, Mixpanel).</li>
        <li><strong>AI Subprocessors:</strong> Providers of AI models and infrastructure (OpenAI, Anthropic, Google AI) used to power lead discovery, enrichment, scoring, and content generation features.</li>
        <li><strong>Integration Partners:</strong> Google (Gmail, Calendar), Telegram, and other services you explicitly connect to your AcquisitionOS account. Data is shared only as necessary to provide the requested integration functionality.</li>
        <li><strong>Team Members:</strong> Members of your organization who are invited to your AcquisitionOS workspace may have access to shared lead data, pipelines, and outreach history based on their assigned roles and permissions.</li>
        <li><strong>Legal Requirements:</strong> When required by law, court order, or governmental regulation, or when we believe in good faith that disclosure is necessary to protect our rights, your safety, or the safety of others.</li>
        <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction, subject to continued protection under this Privacy Policy.</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 4 */}
      <h3 className="text-base font-semibold mt-6 mb-3">4. Data Storage and Security</h3>
      <p className="text-sm leading-relaxed mb-3">
        We implement industry-standard security measures to protect your data:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Encryption:</strong> All data in transit is encrypted using TLS 1.3. Sensitive data at rest is encrypted using AES-256 encryption.</li>
        <li><strong>Access Controls:</strong> Role-based access controls (RBAC) ensure that only authorized personnel can access your data. All access is logged and audited.</li>
        <li><strong>Infrastructure Security:</strong> Our infrastructure runs on SOC 2 Type II certified cloud providers with regular penetration testing and vulnerability assessments.</li>
        <li><strong>Data Isolation:</strong> Each organization&apos;s data is logically isolated to prevent unauthorized cross-tenant access.</li>
        <li><strong>Backup and Recovery:</strong> Regular encrypted backups with point-in-time recovery capabilities are maintained for disaster recovery.</li>
      </ul>
      <p className="text-sm leading-relaxed mt-3">
        While we implement robust security measures, no method of electronic storage or transmission is 100% secure. We cannot guarantee absolute security of your data.
      </p>

      <Separator className="my-6" />

      {/* Section 5 */}
      <h3 className="text-base font-semibold mt-6 mb-3">5. Your Rights</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">5.1 GDPR Rights (EU/EEA Users)</h4>
      <p className="text-sm leading-relaxed mb-3">If you are located in the European Economic Area, you have the following rights under the GDPR:</p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Right of Access (Art. 15):</strong> Request a copy of the personal data we hold about you.</li>
        <li><strong>Right to Rectification (Art. 16):</strong> Request correction of inaccurate personal data.</li>
        <li><strong>Right to Erasure (Art. 17):</strong> Request deletion of your personal data, subject to legal retention requirements.</li>
        <li><strong>Right to Restrict Processing (Art. 18):</strong> Request that we limit how we process your data.</li>
        <li><strong>Right to Data Portability (Art. 20):</strong> Request your data in a machine-readable format for transfer to another service.</li>
        <li><strong>Right to Object (Art. 21):</strong> Object to processing of your data for direct marketing or based on legitimate interests.</li>
        <li><strong>Right Not to Be Subject to Automated Decision-Making (Art. 22):</strong> Request human review of AI-driven decisions that significantly affect you.</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">5.2 CCPA Rights (California Users)</h4>
      <p className="text-sm leading-relaxed mb-3">If you are a California resident, you have the following rights under the CCPA:</p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Right to Know:</strong> Request disclosure of the categories and specific pieces of personal information we have collected, sold, or disclosed.</li>
        <li><strong>Right to Delete:</strong> Request deletion of your personal information, with certain exceptions.</li>
        <li><strong>Right to Opt-Out of Sale:</strong> We do not sell your personal information. You have the right to opt out of any future sale.</li>
        <li><strong>Right to Non-Discrimination:</strong> You will not be discriminated against for exercising your CCPA rights.</li>
      </ul>

      <p className="text-sm leading-relaxed mt-3">
        To exercise any of these rights, contact us at <strong>privacy@acquisitionos.com</strong> or use the built-in privacy controls in your account settings. We will respond to verifiable requests within 30 days (or 45 days if extension is needed).
      </p>

      <Separator className="my-6" />

      {/* Section 6 */}
      <h3 className="text-base font-semibold mt-6 mb-3">6. Data Retention</h3>
      <p className="text-sm leading-relaxed mb-3">
        We retain your personal data only for as long as necessary to fulfill the purposes described in this policy:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Account Data:</strong> Retained for the duration of your account plus 30 days after deletion request, after which it is permanently deleted or anonymized.</li>
        <li><strong>Lead Data:</strong> Retained for the duration of your subscription. Upon account deletion, lead data is anonymized after 90 days.</li>
        <li><strong>Financial Records:</strong> Retained for 7 years as required by tax and financial regulations (PII is anonymized within 30 days of account deletion).</li>
        <li><strong>Usage Logs:</strong> Retained for 90 days, then aggregated and anonymized.</li>
        <li><strong>Communication Data:</strong> Retained for the duration of your account. Upon deletion, communications are permanently removed within 30 days.</li>
        <li><strong>AI-Generated Data:</strong> Retained as part of your account data. Upon deletion, AI-generated insights are anonymized.</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 7 */}
      <h3 className="text-base font-semibold mt-6 mb-3">7. Cookies and Tracking</h3>
      <p className="text-sm leading-relaxed mb-3">
        We use cookies and similar tracking technologies to operate and improve our Service. For detailed information about the cookies we use and how to manage them, please refer to our <button type="button" onClick={() => useLegalStore.getState().openLegal('cookies')} className="text-primary hover:text-primary/80 underline">Cookie Policy</button>.
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Essential Cookies:</strong> Required for authentication, security, and basic platform functionality. Cannot be disabled.</li>
        <li><strong>Analytics Cookies:</strong> Help us understand how users interact with our platform. Can be opted out via cookie preferences.</li>
        <li><strong>Functionality Cookies:</strong> Remember your preferences and settings for a personalized experience.</li>
        <li><strong>Marketing Cookies:</strong> Used for targeted advertising and conversion tracking. Opt-in only.</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 8 */}
      <h3 className="text-base font-semibold mt-6 mb-3">8. International Data Transfers</h3>
      <p className="text-sm leading-relaxed mb-3">
        AcquisitionOS operates globally and your data may be transferred to and processed in countries other than your own. We ensure appropriate safeguards are in place:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Standard Contractual Clauses (SCCs):</strong> We use EU-approved Standard Contractual Clauses for transfers of personal data from the EEA to countries that do not provide an adequate level of data protection.</li>
        <li><strong>Data Processing Agreements:</strong> We maintain DPAs with all subprocessors that process personal data on our behalf.</li>
        <li><strong>Adequacy Decisions:</strong> Where possible, data is stored in regions with EU adequacy decisions.</li>
        <li><strong>Privacy Shield:</strong> For US-based processing, we comply with the EU-US Data Privacy Framework principles.</li>
      </ul>

      <Separator className="my-6" />

      {/* Section 9 */}
      <h3 className="text-base font-semibold mt-6 mb-3">9. Children&apos;s Privacy</h3>
      <p className="text-sm leading-relaxed">
        AcquisitionOS is a B2B platform intended for use by businesses and professionals. Our Service is not directed to children under the age of 16, and we do not knowingly collect personal information from children. If we become aware that we have inadvertently collected personal data from a child under 16, we will take steps to delete such information promptly. If you believe we have collected information from a child, please contact us at <strong>privacy@acquisitionos.com</strong>.
      </p>

      <Separator className="my-6" />

      {/* Section 10 */}
      <h3 className="text-base font-semibold mt-6 mb-3">10. Changes to This Policy</h3>
      <p className="text-sm leading-relaxed">
        We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. We will notify you of material changes by posting the updated policy on our website and, for significant changes, by sending a notification to the email address associated with your account. Your continued use of the Service after the effective date of any changes constitutes your acceptance of the revised Privacy Policy. We encourage you to review this policy periodically.
      </p>

      <Separator className="my-6" />

      {/* Section 11 */}
      <h3 className="text-base font-semibold mt-6 mb-3">11. Contact Information</h3>
      <p className="text-sm leading-relaxed">
        If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:
      </p>
      <ul className="text-sm leading-relaxed list-none pl-0 space-y-1 mt-2">
        <li><strong>Data Protection Officer:</strong> privacy@acquisitionos.com</li>
        <li><strong>General Inquiries:</strong> support@acquisitionos.com</li>
        <li><strong>Postal Address:</strong> AcquisitionOS Inc., 548 Market Street, Suite 36846, San Francisco, CA 94104</li>
        <li><strong>EU Representative:</strong> AcquisitionOS EU B.V., Keizersgracht 520, 1017 EK Amsterdam, Netherlands</li>
      </ul>
      <p className="text-sm leading-relaxed mt-3">
        For GDPR-related complaints, you may also contact your local supervisory authority or the Dutch Data Protection Authority (Autoriteit Persoonsgegevens).
      </p>
    </article>
  );
}

// ════════════════════════════════════════════════════════════════════
// LEGAL CONTENT — Terms of Service
// ════════════════════════════════════════════════════════════════════

function TermsOfServiceContent() {
  return (
    <article className="prose prose-sm dark:prose-invert max-w-none text-justify">
      <p className="text-sm text-muted-foreground mb-6">
        <strong>Effective Date:</strong> March 1, 2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> March 1, 2025
      </p>

      <p className="text-sm leading-relaxed">
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of AcquisitionOS, an AI-powered B2B lead discovery, enrichment, and outreach platform operated by AcquisitionOS Inc. (&quot;Company,&quot; &quot;we,&quot; &quot;our,&quot; or &quot;us&quot;). By accessing or using the Service, you agree to be bound by these Terms.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">1. Acceptance of Terms</h3>
      <p className="text-sm leading-relaxed">
        By creating an account, accessing, or using AcquisitionOS, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service, our <button type="button" onClick={() => useLegalStore.getState().openLegal('privacy')} className="text-primary hover:text-primary/80 underline">Privacy Policy</button>, and our <button type="button" onClick={() => useLegalStore.getState().openLegal('cookies')} className="text-primary hover:text-primary/80 underline">Cookie Policy</button>. If you do not agree to these Terms, you must not use the Service. If you are using the Service on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">2. Description of Service</h3>
      <p className="text-sm leading-relaxed mb-3">
        AcquisitionOS is an AI-powered B2B SaaS platform that provides the following capabilities:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Lead Discovery:</strong> AI-driven search and discovery of business leads based on your ideal customer profile and target criteria.</li>
        <li><strong>Lead Enrichment:</strong> Automated data enrichment, analysis, and AI-powered scoring of discovered leads.</li>
        <li><strong>Outreach &amp; Messaging:</strong> Tools for creating and sending personalized outreach messages, email sequences, and follow-up communications.</li>
        <li><strong>Pipeline Management:</strong> Visual pipeline for tracking leads through your sales process from discovery to close.</li>
        <li><strong>Integrations:</strong> Connectivity with Gmail, Google Calendar, Telegram, and other third-party services.</li>
        <li><strong>AI Assistant:</strong> An AI-powered sales assistant providing coaching, recommendations, and automated task execution.</li>
        <li><strong>Workflow Automation:</strong> Configurable automated workflows for lead nurturing, follow-ups, and multi-step outreach sequences.</li>
        <li><strong>Analytics &amp; Insights:</strong> Performance dashboards, campaign analytics, and AI-generated business insights.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">3. Account Registration</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>You must provide accurate, current, and complete information during registration and keep your account information updated.</li>
        <li>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.</li>
        <li>You must be at least 18 years of age (or the age of majority in your jurisdiction) to create an account.</li>
        <li>You must immediately notify us of any unauthorized use of your account at security@acquisitionos.com.</li>
        <li>We reserve the right to suspend or terminate accounts that violate these Terms or are associated with fraudulent activity.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">4. Acceptable Use</h3>
      <p className="text-sm leading-relaxed mb-3">You agree not to use the Service to:</p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Violate any applicable law, regulation, or third-party right.</li>
        <li>Send unsolicited commercial communications (spam) or engage in any form of harassment.</li>
        <li>Collect or store personal data of individuals without proper consent or legal basis.</li>
        <li>Scrape, harvest, or extract data from third-party websites or services in violation of their terms.</li>
        <li>Interfere with or disrupt the integrity or performance of the Service.</li>
        <li>Attempt to gain unauthorized access to any portion of the Service or related systems.</li>
        <li>Use the Service to discriminate, stalk, threaten, or otherwise harm individuals.</li>
        <li>Reverse engineer, decompile, or disassemble any part of the Service.</li>
        <li>Resell, sublicense, or redistribute the Service without prior written consent.</li>
        <li>Use automated tools (bots, scripts) to access the Service in a manner that exceeds reasonable usage.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">5. Credit System and Payments</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">5.1 Credit-Based Pricing</h4>
      <p className="text-sm leading-relaxed mb-3">
        AcquisitionOS operates on a credit-based pricing model. Different actions consume varying amounts of credits:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Lead Discovery:</strong> Credits consumed per lead found based on search criteria.</li>
        <li><strong>Deep Analysis:</strong> Higher credit cost for AI-powered lead enrichment and scoring.</li>
        <li><strong>Outreach Messages:</strong> Credits consumed per message sent.</li>
        <li><strong>AI Assistant:</strong> Credits consumed per interaction or coaching session.</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">5.2 Subscription Plans</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Free Plan:</strong> Limited monthly credits with basic features. No payment required.</li>
        <li><strong>Pro Plan:</strong> Increased monthly credits with advanced features. Billed monthly or annually.</li>
        <li><strong>Enterprise Plan:</strong> Custom credit allocations, dedicated support, and advanced features. Custom pricing.</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">5.3 Payments and Billing</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Payments are processed through Stripe or Razorpay. All prices are listed in USD or INR as applicable.</li>
        <li>Subscriptions auto-renew at the end of each billing period unless cancelled before the renewal date.</li>
        <li>Credit add-on packs are one-time purchases and do not auto-renew.</li>
        <li>Unused monthly credits do not roll over (except for Pro and Enterprise plans with rollover feature).</li>
        <li>Taxes (including GST for Indian customers) are applied as required by law.</li>
        <li>Refunds are handled on a case-by-case basis. See our refund policy or contact support for details.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">6. Intellectual Property</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>The Service, including all software, design, text, graphics, and underlying AI models, is owned by AcquisitionOS and protected by intellectual property laws.</li>
        <li>You retain ownership of all data you input into the Service, including lead data, outreach content, and business information.</li>
        <li>AI-generated content (lead scores, analysis, suggested messages) is provided to you for your use, but AcquisitionOS retains the right to use anonymized, aggregated patterns to improve our AI models.</li>
        <li>You grant AcquisitionOS a limited, non-exclusive license to process your data solely for the purpose of providing the Service.</li>
        <li>You may not use our trademarks, logos, or brand assets without prior written permission.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">7. Limitation of Liability</h3>
      <p className="text-sm leading-relaxed mb-3">
        TO THE MAXIMUM EXTENT PERMITTED BY LAW:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</li>
        <li>ACQUISITIONOS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY.</li>
        <li>OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM OR RELATED TO THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS PRECEDING THE EVENT GIVING RISE TO THE LIABILITY.</li>
        <li>WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE.</li>
        <li>AI-GENERATED CONTENT IS PROVIDED FOR INFORMATIONAL PURPOSES ONLY AND SHOULD NOT BE RELIED UPON AS LEGAL, FINANCIAL, OR PROFESSIONAL ADVICE.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">8. Indemnification</h3>
      <p className="text-sm leading-relaxed">
        You agree to indemnify, defend, and hold harmless AcquisitionOS and its officers, directors, employees, agents, licensors, and suppliers from and against any claims, actions, demands, liabilities, and settlements including legal fees arising from: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of applicable laws or regulations; (d) content you submit or transmit through the Service; (e) your violation of any rights of a third party, including intellectual property rights; and (f) any outreach or communications sent through the Service that violate anti-spam laws or recipient rights.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">9. Termination</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>By You:</strong> You may terminate your account at any time through your account settings or by contacting support. Upon termination, your right to use the Service ceases immediately.</li>
        <li><strong>By Us:</strong> We may suspend or terminate your account for violation of these Terms, fraudulent activity, or extended inactivity (12+ months) with 30 days&apos; notice.</li>
        <li><strong>Effect of Termination:</strong> Upon termination, we will delete your personal data in accordance with our Privacy Policy and data retention schedule. Financial records are retained as required by law. Credits are forfeited upon termination and are not refundable.</li>
        <li><strong>Survival:</strong> Sections relating to intellectual property, limitation of liability, indemnification, and dispute resolution survive termination.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">10. Dispute Resolution</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Informal Resolution:</strong> Before filing any claim, you agree to contact us at legal@acquisitionos.com and attempt to resolve the dispute informally for at least 30 days.</li>
        <li><strong>Arbitration:</strong> Any disputes arising from these Terms or the Service shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules, except where prohibited by law (e.g., EU consumers may pursue claims in local courts).</li>
        <li><strong>Class Action Waiver:</strong> You agree to resolve disputes with us on an individual basis only and not as a plaintiff or class member in any class or representative action.</li>
        <li><strong>Injunctive Relief:</strong> Nothing in these Terms prevents either party from seeking injunctive relief in any court of competent jurisdiction for breach of intellectual property rights or confidentiality obligations.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">11. Governing Law</h3>
      <p className="text-sm leading-relaxed">
        These Terms are governed by the laws of the State of California, United States, without regard to its conflict of law principles. For users located in the European Union, the mandatory consumer protection laws of your country of residence apply. Any legal proceedings not subject to arbitration shall be brought in the federal or state courts of San Francisco County, California, and you consent to the personal jurisdiction of such courts.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">12. Changes to Terms</h3>
      <p className="text-sm leading-relaxed">
        We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on our website and, for significant changes, by sending an email notification to the address associated with your account at least 30 days before the changes take effect. Your continued use of the Service after the effective date constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, you must discontinue use of the Service and terminate your account.
      </p>

      <p className="text-sm leading-relaxed mt-6">
        For questions about these Terms, contact us at <strong>legal@acquisitionos.com</strong>.
      </p>
    </article>
  );
}

// ════════════════════════════════════════════════════════════════════
// LEGAL CONTENT — Data Processing Agreement
// ════════════════════════════════════════════════════════════════════

function DPAContent() {
  return (
    <article className="prose prose-sm dark:prose-invert max-w-none text-justify">
      <p className="text-sm text-muted-foreground mb-6">
        <strong>Effective Date:</strong> March 1, 2025 &nbsp;|&nbsp; <strong>Version:</strong> 2.0
      </p>

      <p className="text-sm leading-relaxed">
        This Data Processing Agreement (&quot;DPA&quot;) forms part of the Terms of Service between AcquisitionOS Inc. (&quot;Processor&quot;) and the customer entity (&quot;Controller&quot;) and governs the processing of personal data by Processor on behalf of Controller in connection with the use of the AcquisitionOS Service.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">1. Definitions</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>&quot;Personal Data&quot;</strong> means any information relating to an identified or identifiable natural person processed by Processor on behalf of Controller in connection with the Service.</li>
        <li><strong>&quot;Processing&quot;</strong> means any operation performed on Personal Data, whether or not by automated means.</li>
        <li><strong>&quot;Data Subject&quot;</strong> means an identified or identifiable natural person whose Personal Data is processed.</li>
        <li><strong>&quot;Subprocessor&quot;</strong> means any third party engaged by Processor to process Personal Data on behalf of Controller.</li>
        <li><strong>&quot;Data Protection Laws&quot;</strong> means the GDPR, CCPA, and any other applicable data protection legislation.</li>
        <li><strong>&quot;Standard Contractual Clauses&quot; or &quot;SCCs&quot;</strong> means the standard contractual clauses for the transfer of personal data to third countries pursuant to Commission Decision 2021/914.</li>
        <li><strong>&quot;Security Incident&quot;</strong> means any confirmed accidental or unlawful destruction, loss, alteration, unauthorized disclosure of, or access to Personal Data.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">2. Processing Details</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">2.1 Subject Matter and Duration</h4>
      <p className="text-sm leading-relaxed">
        Processor shall process Personal Data for the purpose of providing the AcquisitionOS Service as described in the Terms of Service. This DPA remains in effect for the duration of the Controller&apos;s use of the Service plus the data retention periods specified herein.
      </p>

      <h4 className="text-sm font-semibold mt-4 mb-2">2.2 Nature and Purpose of Processing</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Lead discovery, enrichment, and AI-powered scoring</li>
        <li>Outreach message creation and delivery</li>
        <li>Pipeline management and analytics</li>
        <li>Integration data processing (Gmail, Calendar, Telegram)</li>
        <li>Account management and billing</li>
        <li>Security, fraud prevention, and compliance</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">2.3 Categories of Data Subjects</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Controller&apos;s employees and team members</li>
        <li>Controller&apos;s leads and prospects (business contacts)</li>
        <li>End users of Controller&apos;s services (if applicable)</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">2.4 Categories of Personal Data</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Identification data (name, email, phone, job title)</li>
        <li>Business data (company name, industry, revenue, size)</li>
        <li>Contact data (email addresses, phone numbers, social profiles)</li>
        <li>Usage data (interaction data, platform usage patterns)</li>
        <li>Communication data (outreach messages, email content)</li>
        <li>Financial data (billing information, payment records)</li>
        <li>AI-generated data (scores, analysis, recommendations)</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">3. Data Controller / Processor Obligations</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">3.1 Controller Obligations</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Controller is responsible for ensuring lawful processing of Personal Data and has provided all necessary notices and obtained all necessary consents.</li>
        <li>Controller shall ensure that its instructions to Processor comply with Data Protection Laws.</li>
        <li>Controller is responsible for ensuring that Data Subjects have been informed of the Processing activities as required by law.</li>
      </ul>

      <h4 className="text-sm font-semibold mt-4 mb-2">3.2 Processor Obligations</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Processor shall process Personal Data only on documented instructions from Controller, including with regard to transfers of Personal Data to a third country.</li>
        <li>Processor shall ensure that persons authorized to process Personal Data have committed themselves to confidentiality.</li>
        <li>Processor shall not engage another processor without prior specific or general written authorization of Controller.</li>
        <li>Processor shall assist Controller in ensuring compliance with obligations related to data security, breach notification, and data subject rights.</li>
        <li>Processor shall delete or return all Personal Data to Controller upon termination of the Service, subject to legal retention requirements.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">4. Subprocessors</h3>
      <p className="text-sm leading-relaxed mb-3">
        Controller provides general authorization for Processor to engage the following categories of subprocessors:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Cloud Infrastructure:</strong> Amazon Web Services (AWS), Vercel — hosting and compute</li>
        <li><strong>Payment Processing:</strong> Stripe, Razorpay — billing and payment management</li>
        <li><strong>AI Services:</strong> OpenAI, Anthropic, Google AI — AI model inference and processing</li>
        <li><strong>Email Delivery:</strong> Gmail SMTP, SendGrid — transactional and outreach email delivery</li>
        <li><strong>Analytics:</strong> PostHog — product analytics</li>
        <li><strong>Monitoring:</strong> Sentry — error tracking and performance monitoring</li>
        <li><strong>Communication:</strong> Telegram API — notification delivery</li>
      </ul>
      <p className="text-sm leading-relaxed mt-3">
        Processor shall notify Controller of any intended changes concerning the addition or replacement of subprocessors, giving Controller the opportunity to object to such changes. A current list of subprocessors is available upon request at <strong>dpa@acquisitionos.com</strong>.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">5. Data Security</h3>
      <p className="text-sm leading-relaxed mb-3">
        Processor implements appropriate technical and organizational measures to ensure a level of security appropriate to the risk, including:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Encryption of Personal Data in transit (TLS 1.3) and at rest (AES-256)</li>
        <li>Role-based access controls with multi-factor authentication</li>
        <li>Regular security assessments and penetration testing</li>
        <li>Employee security training and background checks</li>
        <li>Incident response and business continuity plans</li>
        <li>Network segmentation and firewall protection</li>
        <li>Regular backup and disaster recovery procedures</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">6. Data Breach Notification</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Processor shall notify Controller without undue delay and no later than 48 hours after becoming aware of a Security Incident.</li>
        <li>Notification shall include: the nature of the breach, categories and approximate number of Data Subjects affected, likely consequences, and measures taken or proposed to address the breach.</li>
        <li>Processor shall cooperate with Controller in investigating and mitigating the Security Incident.</li>
        <li>Processor shall not inform any third party of a Security Incident without first obtaining Controller&apos;s consent, unless required by law.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">7. Data Subject Rights</h3>
      <p className="text-sm leading-relaxed mb-3">
        Processor shall assist Controller in fulfilling its obligations to respond to Data Subject requests for exercising their rights under Data Protection Laws:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Access:</strong> Provide Data Subjects with a copy of their Personal Data upon verified request.</li>
        <li><strong>Rectification:</strong> Correct inaccurate Personal Data within 5 business days.</li>
        <li><strong>Erasure:</strong> Delete Personal Data within 30 days of verified request, subject to legal retention requirements.</li>
        <li><strong>Portability:</strong> Export Personal Data in a machine-readable format (JSON/CSV) within 15 business days.</li>
        <li><strong>Restriction:</strong> Temporarily halt processing of Personal Data pending resolution of a Data Subject&apos;s concern.</li>
        <li><strong>Objection:</strong> Cease processing for specific purposes when a valid objection is raised.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">8. Audit Rights</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Controller may audit Processor&apos;s compliance with this DPA, subject to reasonable notice (at least 30 days) and confidentiality requirements.</li>
        <li>Processor shall make available to Controller all information necessary to demonstrate compliance and allow for and contribute to audits, including inspections, conducted by Controller or a mandated auditor.</li>
        <li>Processor shall maintain records of processing activities as required by Article 30 of the GDPR.</li>
        <li>Processor shall provide annual SOC 2 Type II reports or equivalent certifications upon request.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">9. Data Transfer</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>Processor shall not transfer Personal Data to a third country without appropriate safeguards in place.</li>
        <li>For transfers from the EEA, the Standard Contractual Clauses (2021/914) are incorporated by reference into this DPA.</li>
        <li>Processor has implemented supplementary measures as recommended by the EDPB for transfers to the United States.</li>
        <li>Controller may request details of the specific safeguards applicable to each transfer.</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">10. Term and Termination</h3>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li>This DPA remains in effect for the duration of the Controller&apos;s use of the Service.</li>
        <li>Upon termination, Processor shall, at Controller&apos;s choice, delete or return all Personal Data within 90 days, unless retention is required by law.</li>
        <li>Processor shall certify deletion of Personal Data upon Controller&apos;s written request.</li>
        <li>Financial and legal records containing Personal Data shall be retained as required by applicable law with PII anonymized within 30 days of termination.</li>
      </ul>

      <p className="text-sm leading-relaxed mt-6">
        For DPA-related inquiries, contact: <strong>dpa@acquisitionos.com</strong>
      </p>
    </article>
  );
}

// ════════════════════════════════════════════════════════════════════
// LEGAL CONTENT — Cookie Policy
// ════════════════════════════════════════════════════════════════════

function CookiePolicyContent() {
  return (
    <article className="prose prose-sm dark:prose-invert max-w-none text-justify">
      <p className="text-sm text-muted-foreground mb-6">
        <strong>Effective Date:</strong> March 1, 2025 &nbsp;|&nbsp; <strong>Last Updated:</strong> March 1, 2025
      </p>

      <p className="text-sm leading-relaxed">
        This Cookie Policy explains how AcquisitionOS Inc. (&quot;we,&quot; &quot;our,&quot; or &quot;us&quot;) uses cookies and similar technologies when you visit and use our AI-powered B2B lead discovery and outreach platform. This policy should be read alongside our <button type="button" onClick={() => useLegalStore.getState().openLegal('privacy')} className="text-primary hover:text-primary/80 underline">Privacy Policy</button>.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">1. What Are Cookies?</h3>
      <p className="text-sm leading-relaxed">
        Cookies are small text files that are stored on your device (computer, tablet, or mobile phone) when you visit a website. They are widely used to make websites work more efficiently, provide a better user experience, and supply information to the owners of the site. Cookies can be &quot;persistent&quot; (stored until they expire or you delete them) or &quot;session&quot; (deleted when you close your browser). In addition to cookies, we may also use similar technologies such as web beacons, pixel tags, and local storage.
      </p>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">2. Types of Cookies We Use</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">2.1 Essential Cookies</h4>
      <p className="text-sm leading-relaxed mb-3">
        These cookies are strictly necessary for the operation of our platform. They enable core functionality such as authentication, security, and account access. You cannot opt out of these cookies.
      </p>
      <div className="overflow-x-auto">
        <table className="text-xs w-full border-collapse">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2 pr-4 font-semibold">Cookie Name</th>
              <th className="text-left py-2 pr-4 font-semibold">Purpose</th>
              <th className="text-left py-2 pr-4 font-semibold">Duration</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b"><td className="py-1.5 pr-4">session_token</td><td className="py-1.5 pr-4">Maintains your authenticated session</td><td className="py-1.5 pr-4">Session</td></tr>
            <tr className="border-b"><td className="py-1.5 pr-4">csrf_token</td><td className="py-1.5 pr-4">Prevents cross-site request forgery attacks</td><td className="py-1.5 pr-4">Session</td></tr>
            <tr className="border-b"><td className="py-1.5 pr-4">cookie_consent</td><td className="py-1.5 pr-4">Stores your cookie preferences</td><td className="py-1.5 pr-4">1 year</td></tr>
            <tr><td className="py-1.5 pr-4">refresh_token</td><td className="py-1.5 pr-4">Enables session persistence across browser restarts</td><td className="py-1.5 pr-4">30 days</td></tr>
          </tbody>
        </table>
      </div>

      <h4 className="text-sm font-semibold mt-6 mb-2">2.2 Analytics Cookies</h4>
      <p className="text-sm leading-relaxed mb-3">
        These cookies help us understand how visitors interact with our platform, allowing us to improve the user experience and optimize our service. They are optional and can be opted out.
      </p>
      <div className="overflow-x-auto">
        <table className="text-xs w-full border-collapse">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2 pr-4 font-semibold">Cookie Name</th>
              <th className="text-left py-2 pr-4 font-semibold">Purpose</th>
              <th className="text-left py-2 pr-4 font-semibold">Duration</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b"><td className="py-1.5 pr-4">_ph_pcx</td><td className="py-1.5 pr-4">PostHog analytics — page views and user flows</td><td className="py-1.5 pr-4">1 year</td></tr>
            <tr className="border-b"><td className="py-1.5 pr-4">_ph_ses</td><td className="py-1.5 pr-4">PostHog session tracking</td><td className="py-1.5 pr-4">30 minutes</td></tr>
            <tr><td className="py-1.5 pr-4">ajs_*_id</td><td className="py-1.5 pr-4">Analytics user identification</td><td className="py-1.5 pr-4">1 year</td></tr>
          </tbody>
        </table>
      </div>

      <h4 className="text-sm font-semibold mt-6 mb-2">2.3 Functionality Cookies</h4>
      <p className="text-sm leading-relaxed mb-3">
        These cookies enable the platform to remember choices you make (such as theme preference, sidebar state, or navigation history) and provide enhanced, personalized features.
      </p>
      <div className="overflow-x-auto">
        <table className="text-xs w-full border-collapse">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2 pr-4 font-semibold">Cookie Name</th>
              <th className="text-left py-2 pr-4 font-semibold">Purpose</th>
              <th className="text-left py-2 pr-4 font-semibold">Duration</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b"><td className="py-1.5 pr-4">theme_preference</td><td className="py-1.5 pr-4">Stores your light/dark theme selection</td><td className="py-1.5 pr-4">1 year</td></tr>
            <tr className="border-b"><td className="py-1.5 pr-4">sidebar_state</td><td className="py-1.5 pr-4">Remembers sidebar collapsed/expanded state</td><td className="py-1.5 pr-4">Session</td></tr>
            <tr><td className="py-1.5 pr-4">onboarding_status</td><td className="py-1.5 pr-4">Tracks onboarding completion status</td><td className="py-1.5 pr-4">1 year</td></tr>
          </tbody>
        </table>
      </div>

      <h4 className="text-sm font-semibold mt-6 mb-2">2.4 Marketing Cookies</h4>
      <p className="text-sm leading-relaxed mb-3">
        These cookies are used to track visitors across websites to display relevant advertisements and measure the effectiveness of our marketing campaigns. They are optional and require your explicit consent.
      </p>
      <div className="overflow-x-auto">
        <table className="text-xs w-full border-collapse">
          <thead>
            <tr className="border-b">
              <th className="text-left py-2 pr-4 font-semibold">Cookie Name</th>
              <th className="text-left py-2 pr-4 font-semibold">Purpose</th>
              <th className="text-left py-2 pr-4 font-semibold">Duration</th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b"><td className="py-1.5 pr-4">_gcl_au</td><td className="py-1.5 pr-4">Google Ads conversion tracking</td><td className="py-1.5 pr-4">90 days</td></tr>
            <tr className="border-b"><td className="py-1.5 pr-4">_fbp</td><td className="py-1.5 pr-4">Facebook pixel — ad targeting</td><td className="py-1.5 pr-4">90 days</td></tr>
            <tr><td className="py-1.5 pr-4">utm_*</td><td className="py-1.5 pr-4">Campaign attribution tracking</td><td className="py-1.5 pr-4">Session</td></tr>
          </tbody>
        </table>
      </div>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">3. How to Manage Cookies</h3>

      <h4 className="text-sm font-semibold mt-4 mb-2">3.1 Cookie Consent Banner</h4>
      <p className="text-sm leading-relaxed">
        When you first visit AcquisitionOS, we present a cookie consent banner that allows you to accept all cookies, reject non-essential cookies, or manage your preferences in detail. You can access your cookie preferences at any time through the Settings panel under Data &amp; Privacy.
      </p>

      <h4 className="text-sm font-semibold mt-4 mb-2">3.2 Browser Settings</h4>
      <p className="text-sm leading-relaxed">
        Most web browsers allow you to control cookies through their settings. You can typically find these settings in the &quot;Options,&quot; &quot;Preferences,&quot; or &quot;Settings&quot; menu of your browser. You can set your browser to reject all cookies, accept only first-party cookies, or delete cookies when you close your browser. Note that disabling cookies may affect the functionality of the AcquisitionOS platform.
      </p>

      <h4 className="text-sm font-semibold mt-4 mb-2">3.3 Opt-Out Links</h4>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Google Analytics:</strong> https://tools.google.com/dlpage/gaoptout</li>
        <li><strong>Facebook Pixel:</strong> https://www.facebook.com/help/568137493302217</li>
        <li><strong>PostHog:</strong> Available through in-app cookie preferences</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">4. Third-Party Cookies</h3>
      <p className="text-sm leading-relaxed mb-3">
        Some cookies are placed by third-party services that appear on our pages. We do not control these cookies and recommend reviewing the privacy policies of these third parties:
      </p>
      <ul className="text-sm leading-relaxed list-disc pl-5 space-y-1.5">
        <li><strong>Stripe:</strong> Payment processing cookies — https://stripe.com/privacy</li>
        <li><strong>Razorpay:</strong> Payment processing cookies — https://razorpay.com/privacy</li>
        <li><strong>Google (Gmail/Calendar):</strong> Integration authentication — https://policies.google.com/privacy</li>
        <li><strong>Telegram:</strong> Notification integration — https://telegram.org/privacy</li>
        <li><strong>PostHog:</strong> Product analytics — https://posthog.com/privacy</li>
      </ul>

      <Separator className="my-6" />

      <h3 className="text-base font-semibold mt-6 mb-3">5. Changes to This Policy</h3>
      <p className="text-sm leading-relaxed">
        We may update this Cookie Policy from time to time to reflect changes in the cookies we use or for other operational, legal, or regulatory reasons. We will notify you of any material changes by posting the updated policy on our website and updating the &quot;Last Updated&quot; date. We encourage you to review this Cookie Policy periodically.
      </p>

      <p className="text-sm leading-relaxed mt-6">
        For questions about our use of cookies, contact us at <strong>privacy@acquisitionos.com</strong>.
      </p>
    </article>
  );
}

// ════════════════════════════════════════════════════════════════════
// MAIN LEGAL PAGES DIALOG COMPONENT
// ════════════════════════════════════════════════════════════════════

const LEGAL_TABS: { value: LegalPage; label: string; icon: React.ElementType }[] = [
  { value: 'privacy', label: 'Privacy Policy', icon: Shield },
  { value: 'terms', label: 'Terms of Service', icon: FileText },
  { value: 'dpa', label: 'DPA', icon: Lock },
  { value: 'cookies', label: 'Cookie Policy', icon: Cookie },
];

/*
 * MOBILE ACTIVE-TAB VISIBILITY
 * ────────────────────────────
 * On narrow screens the tab strip is a horizontal scroll container, and
 * `activePage` can be set OUTSIDE the strip (Settings → Legal cards,
 * footer links). When that happens the newly-active tab may sit scrolled
 * out of view, leaving the active state invisible. This sub-component
 * owns the strip and scrolls it just enough to keep the active tab fully
 * in view. It only touches the strip's own scrollLeft — never ancestors
 * (page/body) — so the layout stays put. Desktop is unaffected: the
 * strip shows all tabs without scrolling, so the adjustment is a no-op.
 *
 * NOTE: this MUST be a child component (not an effect in LegalPages).
 * Radix Dialog mounts its portal content one render late (Presence), so
 * on the parent commit where `open` flips true the strip DOM does not
 * exist yet and parent-level refs are null. As a child of DialogContent
 * this component mounts WITH the strip, so its own effects always see
 * the real nodes.
 */
function LegalTabStrip({ activePage }: { activePage: LegalPage }) {
  const stripRef = useRef<HTMLDivElement | null>(null);
  const activeTabRef = useRef<HTMLButtonElement | null>(null);

  useEffect(() => {
    const strip = stripRef.current;
    const tab = activeTabRef.current;
    if (!strip || !tab) return;
    const raf = requestAnimationFrame(() => {
      const tabRect = tab.getBoundingClientRect();
      const stripRect = strip.getBoundingClientRect();
      const pad = 12; // keep a little breathing room past the edge
      if (tabRect.left < stripRect.left) {
        strip.scrollLeft -= stripRect.left - tabRect.left + pad;
      } else if (tabRect.right > stripRect.right) {
        strip.scrollLeft += tabRect.right - stripRect.right + pad;
      }
    });
    return () => cancelAnimationFrame(raf);
  }, [activePage]);

  return (
    <div ref={stripRef} className="overflow-x-auto custom-scrollbar -mx-1 px-1 max-w-full">
      <TabsList className="flex w-max bg-transparent h-auto p-0 gap-0">
        {LEGAL_TABS.map((tab) => {
          const Icon = tab.icon;
          const isActive = activePage === tab.value;
          return (
            <TabsTrigger
              key={tab.value}
              value={tab.value}
              ref={isActive ? activeTabRef : undefined}
              className="flex items-center gap-1.5 px-3 py-2.5 text-xs sm:text-sm rounded-t-lg border-b-2 border-transparent data-[state=active]:border-primary data-[state=active]:bg-primary/5 data-[state=active]:text-primary whitespace-nowrap transition-colors"
            >
              <Icon className="h-3.5 w-3.5 shrink-0" />
              <span className="whitespace-nowrap">{tab.label}</span>
            </TabsTrigger>
          );
        })}
      </TabsList>
    </div>
  );
}

export default function LegalPages() {
  const { open, activePage, closeLegal, setActivePage } = useLegalStore();

  return (
    <Dialog open={open} onOpenChange={(isOpen) => { if (!isOpen) closeLegal(); }}>
      {/*
        LEGAL DIALOG LAYOUT — MOBILE-FIRST FULL-SCROLL FIX
        ────────────────────────────────────────────────────────
        • showCloseButton={false}: the floating X is removed; the explicit
          "Back" button in the header is the single close affordance.
        • Mobile (<sm): the dialog becomes a full-screen sheet
          (h-[100dvh], w-full, rounded-none) so the ENTIRE document is
          reachable — no fixed-height clipping, no inaccessible bottom
          content at 320/375/390/430px.
        • Desktop (≥sm): centered 90vh dialog, as before.
        • Inner layout is flex-column with a min-h-0 scroll region, so
          the content area always fits whatever header height the
          current viewport produces (no more h-[calc(90vh-…)] guessing).
      */}
      <DialogContent
        showCloseButton={false}
        overlayClassName="z-[300]"
        className="z-[300] max-w-4xl w-full sm:w-[95vw] h-[100dvh] sm:h-[90vh] p-0 gap-0 overflow-hidden flex flex-col rounded-none sm:rounded-lg top-0 left-0 translate-x-0 translate-y-0 sm:top-[50%] sm:left-[50%] sm:translate-x-[-50%] sm:translate-y-[-50%]"
      >
        <DialogHeader className="sr-only">
          <DialogTitle>Legal Documents</DialogTitle>
          <DialogDescription>
            Review our legal documents including Privacy Policy, Terms of Service, Data Processing Agreement, and Cookie Policy.
          </DialogDescription>
        </DialogHeader>

        <Tabs
          value={activePage}
          onValueChange={(v) => setActivePage(v as LegalPage)}
          className="flex flex-col flex-1 min-h-0"
        >
          {/* Tab Header — fixed row, never clipped */}
          <div className="border-b px-4 sm:px-6 pt-4 pb-0 shrink-0 min-w-0">
            <div className="flex items-center justify-between gap-2 mb-3">
              <h2 className="text-base sm:text-lg font-semibold truncate min-w-0">Legal Documents</h2>
              <Button
                variant="ghost"
                size="sm"
                onClick={closeLegal}
                className="text-muted-foreground hover:text-foreground shrink-0"
                aria-label="Back — close legal documents"
              >
                <ArrowLeft className="h-4 w-4 mr-1" />
                Back
              </Button>
            </div>
            {/* Mobile: horizontally scrollable tabs (touch-friendly, no wrap/overlap);
                auto-keeps the ACTIVE tab in view — see LegalTabStrip. */}
            <LegalTabStrip activePage={activePage} />
          </div>

          {/* Tab Content — the single scroll owner; flex-1 + min-h-0 fills
              all remaining space at ANY viewport, so the FULL document is
              always reachable by scrolling (no clipped bottom on mobile). */}
          <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain custom-scrollbar">
            <div className="px-4 sm:p-8 py-5 sm:py-8 pb-10 sm:pb-8 max-w-full overflow-x-hidden [&_article]:[overflow-wrap:anywhere]">
              <TabsContent value="privacy" className="mt-0">
                <h2 className="text-xl font-bold mb-1">Privacy Policy</h2>
                <p className="text-sm text-muted-foreground mb-6">How AcquisitionOS collects, uses, and protects your personal information.</p>
                <PrivacyPolicyContent />
              </TabsContent>

              <TabsContent value="terms" className="mt-0">
                <h2 className="text-xl font-bold mb-1">Terms of Service</h2>
                <p className="text-sm text-muted-foreground mb-6">The terms and conditions governing your use of AcquisitionOS.</p>
                <TermsOfServiceContent />
              </TabsContent>

              <TabsContent value="dpa" className="mt-0">
                <h2 className="text-xl font-bold mb-1">Data Processing Agreement</h2>
                <p className="text-sm text-muted-foreground mb-6">Agreement governing the processing of personal data on your behalf.</p>
                <DPAContent />
              </TabsContent>

              <TabsContent value="cookies" className="mt-0">
                <h2 className="text-xl font-bold mb-1">Cookie Policy</h2>
                <p className="text-sm text-muted-foreground mb-6">How AcquisitionOS uses cookies and similar tracking technologies.</p>
                <CookiePolicyContent />
              </TabsContent>
            </div>
          </div>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
